# Generated by Django 3.2.6 on 2021-09-08 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='logo',
        ),
        migrations.AddField(
            model_name='activity',
            name='icon',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
